name: Pull request workflow

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

     - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
            ${{ runner.os }}-

      - name: install deps
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --check-files --frozen-lockfile --non-interactive

      - name: tsc
        run: yarn tsc

      - name: test
        run: yarn test

      - name: lint
        run: yarn lint

      - name: md
        run: yarn workspace docs lint-md

      - name: build
        run: yarn build
